title: Mi Portafolio con ORM
description: Portafolio con pruebas integradas de ORM
baseurl: ""
url: "https://amehrezconti.github.io"  # Reemplaza con tu usuario
theme: minima

# Permite que GitHub Pages sirva archivos JSON
include:
  - _data/projects.json
  - _data/skills.json
  - assets/js/orm.js

# Configuración para GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
